apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  sources:
   - repoURL: https://github.com/argoproj/argocd-example-apps
     targetRevision: master
     path: helm-guestbook
     helm:
       valueFiles:
         - "$values/values/values.yaml"    
   - repoURL: https://github.com/mohamedragab2024/gitops-apps.git
     targetRevision: main
     ref: values
   - repoURL: https://github.com/mohamedragab2024/gitops-apps.git
     targetRevision: main
     path: hooks
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
