apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: helm-guestbook
  namespace: argocd
spec:
  project: default
  sources:
   - repoURL: https://github.com/argoproj/argocd-example-apps
     targetRevision: master
     path: helm-guestbook
     helm:
       valueFiles:
         - "$values/values/values.yaml"    
   - repoURL: https://github.com/mohamedragab2024/gitops-apps.git
     targetRevision: main
     ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  resources:
    - apiVersion: batch/v1
      kind: Job
      metadata:
        name: post-sync-echo-job
        annotations:
          argocd.argoproj.io/hook: PostSync
          argocd.argoproj.io/hook-delete-policy: HookSucceeded
      spec:
        template:
          spec:
            containers:
              - name: echo-container
                image: busybox
                command:
                  - "sh"
                  - "-c"
                  - |
                    echo "Sleeping for 1 minute..."
                    sleep 60
                    echo "This is a post-sync hook after sleep!"
            restartPolicy: Never
